<?php
function triangle_tracker_menu() {
    $items['triangle_tracker'] = array(
        'title' => "Track Your Triangle",
        'page callback' => 'drupal_get_form',
        'page arguments' => array('triangle_tracker_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['triangle_tracker_success_page'] = array(
        'title' => 'Yes, you did it!',
        'page callback' => 'triangle_tracker_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function triangle_tracker_form() {
    $form['first_side'] = array(
        '#title' => 'First Side',
        '#type' => 'textfield',
        '#description' => t('Enter the first side of your triangle.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['second_side'] = array(
        '#title' => 'Second Side',
        '#type' => 'textfield',
        '#description' => t('Enter the second side of your triangle.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['third_side'] = array(
        '#title' => 'Third Side',
        '#type' => 'textfield',
        '#description' => t('Enter the third side of your triangle.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' =>'submit',
        '#value' => 'Submit',
    );
    return $form;
}

function triangle_tracker_form_submit($form, &$form_state) {
    $first_side = $form_state['values']['first_side'];
    $second_side = $form_state['values']['second_side'];
    $third_side = $form_state['values']['third_side'];

    if(($first_side + $second_side <= $third_side) || ($second_side + $third_side <= $first_sides) || ($first_side + $third_side <= $second_side)) {
        $result = "This is not a triangle! The sum of two sides must be greater than the third.";
    } elseif(($first_side == $second_side) && ($second_side == $third_side)) {
        $result = "Equilateral triangle";
    } elseif (($first_side == $second_side) || ($second_side == $third_side) ||
    ($first_side == $third_side)) {
        $result = "Isosceles triangle";
    } else {
        $result = "Scalene triangle";
    }
    $_SESSION['result'] = $result;
    $form_state['redirect'] = 'triangle_tracker_success_page';
}

function triangle_tracker_success() {
    return $_SESSION['result'];
}
