<?php

$GLOBALS['states'] = array();
$GLOBALS['states'] = array(
    'AL' => 'Alabama',
    'AK' => 'Alaska',
    'AZ' => 'Arizona',
    'AR' => 'Arkansas',
    'CA' => 'California',
    'CO' => 'Colorado',
    'CT' => 'Connecticut',
    'DE' => 'Delaware',
    'FL' => 'Florida',
    'GA' => 'Georgia',
    'HI' => 'Hawaii',
    'ID' => 'Idaho',
    'IL' => 'Illinois',
    'IN' => 'Indiana',
    'IA' => 'Iowa',
    'KS' => 'Kansas',
    'KY' => 'Kentucky',
    'LA' => 'Louisiana',
    'ME' => 'Maine',
    'MD' => 'Maryland',
    'MA' => 'Massachusetts',
    'MI' => 'Michigan',
    'MN' => 'Minnesota',
    'MS' => 'Mississippi',
    'MO' => 'Missouri',
    'MT' => 'Montana',
    'NE' => 'Nebraska',
    'NV' => 'Nevada',
    'NH' => 'New Hampshire',
    'NJ' => 'New Jersey',
    'NM' => 'New Mexico',
    'NY' => 'New York',
    'NC' => 'North Carolina',
    'ND' => 'North Dakota',
    'OH' => 'Ohio',
    'OK' => 'Oklahoma',
    'OR' => 'Oregon',
    'PA' => 'Pennsylvania',
    'RI' => 'Rhode Island',
    'SC' => 'South Carolina',
    'SD' => 'South Dakota',
    'TN' => 'Tennessee',
    'TX' => 'Texas',
    'UT' => 'Utah',
    'VT' => 'Vermont',
    'VA' => 'Virginia',
    'WA' => 'Washington',
    'WV' => 'West Virginia',
    'WI' => 'Wisconsin',
    'WY' => 'Wyoming',
    'DC' => 'District of Columbia',
    'AS' => 'American Samoa',
    'GU' => 'Guam',
    'MP' => 'Northern Mariana Islands',
    'PR' => 'Puerto Rico',
    'UM' => 'United States Minor Outlying Islands',
    'VI' => 'Virgin Islands, U.S.',
);

function state_poll_menu() {
    $items['state_poll'] = array(
        'title' => "Ice Cream by State",
        'page callback' => 'drupal_get_form',
        'page arguments' => array('state_poll_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['state_poll_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'state_poll_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function state_poll_form() {
    $form['ice_cream'] = array(
        '#title' => "Ice Cream Flavor",
        '#type' => 'textfield',
        '#description' => t('Enter your favorite ice cream flavor.'),
        '#required' => TRUE,
    );
    $form['state'] = array(
        '#title' => "Enter your State.",
        '#type' => 'textfield',
        '#description' => 'Enter your State.',
        '#element_validate' => array('element_validate_us_state'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}


function state_poll_form_submit($form, &$form_state) {
    $ice_cream = $form_state['values']['ice_cream'];
    $state = $form_state['values']['state'];


    if (strlen($state) < 3) {
        $state = strtoupper($state);
        foreach ($GLOBALS['states'] as $new_state => $value) {
            if ($state == $new_state) {
                $state = $value;
            }
        }
    } else {
    $state = strtolower($state);
    $state = ucwords($state);
    }

    $result = "Thank you! You love " . $ice_cream . " ice cream in the state of " . $state . ".";
    $_SESSION['result'] = $result;
    $form_state['redirect'] = 'state_poll_success_page';
}

function state_poll_success() {
    var_dump($_SESSION['mydebugthing']);
    return (string) $_SESSION['result'];
}

function element_validate_us_state($element) {
    $state = $element['#value'];
    if (strlen($state) < 3) {
        $state = strtoupper($state);
    } else {
        $state = strtolower($state);
        $state = ucwords($state);
    }
    // $states = array(
    //     'AL','Alabama',
    //     'AK','Alaska',
    //     'AZ','Arizona',
    //     'AR','Arkansas',
    //     'CA','California',
    //     'CO','Colorado',
    //     'CT','Connecticut',
    //     'DE','Delaware',
    //     'FL','Florida',
    //     'GA','Georgia',
    //     'HI','Hawaii',
    //     'ID','Idaho',
    //     'IL','Illinois',
    //     'IN','Indiana',
    //     'IA','Iowa',
    //     'KS','Kansas',
    //     'KY','Kentucky',
    //     'LA','Louisiana',
    //     'ME','Maine',
    //     'MD','Maryland',
    //     'MA','Massachusetts',
    //     'MI','Michigan',
    //     'MN','Minnesota',
    //     'MS','Mississippi',
    //     'MO','Missouri',
    //     'MT','Montana',
    //     'NE','Nebraska',
    //     'NV','Nevada',
    //     'NH','New Hampshire',
    //     'NJ','New Jersey',
    //     'NM','New Mexico',
    //     'NY','New York',
    //     'NC','North Carolina',
    //     'ND','North Dakota',
    //     'OH','Ohio',
    //     'OK','Oklahoma',
    //     'OR','Oregon',
    //     'PA','Pennsylvania',
    //     'RI','Rhode Island',
    //     'SC','South Carolina',
    //     'SD','South Dakota',
    //     'TN','Tennessee',
    //     'TX','Texas',
    //     'UT','Utah',
    //     'VT','Vermont',
    //     'VA','Virginia',
    //     'WA','Washington',
    //     'WV','West Virginia',
    //     'WI','Wisconsin',
    //     'WY','Wyoming',
    //     'DC','District of Columbia',
    //     'AS','American Samoa',
    //     'GU','Guam',
    //     'MP','Northern Mariana Islands',
    //     'PR','Puerto Rico',
    //     'UM','United States Minor Outlying Islands',
    //     'VI','Virgin Islands, U.S.',
    // );
    // input $state: "California"
    // 1: $new_state = AL $value = Alabama
    // How to validate with a for each loop

    $_SESSION['mydebugthing'] = array();
    $is_error = TRUE;
    foreach ($GLOBALS['states'] as $abbreviation => $full_name) {
        if (($state == $abbreviation) || ($state == $full_name)) {
            $is_error = FALSE;
            break;
        }
    }
    if($is_error) {
        form_set_error($state, t('Please enter a valid state.'));
    }
    // how to validate with PHP commands:
    // $full_state_names = array_values($GLOBALS['states']);
    // $state_abbreviations = array_keys($GLOBALS['states']);
    // $_SESSION['mydebugthing'][] = $full_state_names;
    // $_SESSION['mydebugthing'][] = $state_abbreviations;

    // if(!in_array($state, $full_state_names) && !in_array($state, $state_abbreviations)) {
    //     form_set_error($state, t('Please enter a valid state.'));
    // }
    // if((array_key_exists($state, $GLOBALS['states']) === false)) {
    //     // form_set_error($state, t('Please enter a valid state.'));
    // }
}
