<?php
function greeting_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => "Hello Friend!",
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell'] = array(
        'title' => 'Farewell Friend!',
        'page callback' => 'say_farewell',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

// var_dump($user->roles);
function say_hello() {
    $user = $GLOBALS['user'];
    if($user->roles[2] && $user->roles[3]) {
        return '<p>Hello dear admin! Welcome to your domain.</p>';
    } elseif ($user->roles[2]) {
        return '<p>Nice to see you, welcome back.</p>';
    };
}

function say_farewell() {
    return '<p>Fare thee well my dear friend!</p>';
}

function greeting_user_login() {
    $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout() {
    $_GET['destination'] = 'farewell';
}
